# Generated by Django 3.1.3 on 2020-11-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=50)),
                ('studID', models.CharField(max_length=50)),
            ],
        ),
    ]
